
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GetNoteSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  clientId: "",
  rootFolder: "Get",
  notesFolder: "Notes",
  attachmentsFolder: "Attachments",
  timelineNote: "Get/Get Timeline.md",
  canvasFile: "Get/Get Notes.canvas",
  includeReferenceText: true,
  includeOriginalText: true,
  inlineChildNotes: true,
  downloadAttachments: true,
  autoSyncOnStartup: false,
  autoSyncIntervalHours: 0,
  generateTimeline: true,
  generateCanvas: false
};
var GetSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Get Note Sync" });
    containerEl.createEl("p", {
      text: "Use the Get OpenAPI to sync notes directly into your Obsidian vault."
    });
    new import_obsidian.Setting(containerEl).setName("Get API Key").setDesc("Used as the Authorization header when requesting the Get OpenAPI.").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Paste your Get API Key");
      text.setValue(this.plugin.settings.apiKey);
      text.onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Get Client ID").setDesc("Sent as the X-Client-ID header.").addText((text) => {
      text.setPlaceholder("Paste your Get Client ID");
      text.setValue(this.plugin.settings.clientId);
      text.onChange(async (value) => {
        this.plugin.settings.clientId = value.trim();
        await this.plugin.savePluginData();
      });
    });
    containerEl.createEl("h3", { text: "Storage" });
    new import_obsidian.Setting(containerEl).setName("Root folder").setDesc("All generated files will be placed under this vault folder.").addText((text) => {
      text.setPlaceholder("Get");
      text.setValue(this.plugin.settings.rootFolder);
      text.onChange(async (value) => {
        this.plugin.settings.rootFolder = value.trim() || DEFAULT_SETTINGS.rootFolder;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Notes folder").setDesc("Created under the root folder and grouped by date.").addText((text) => {
      text.setPlaceholder("Notes");
      text.setValue(this.plugin.settings.notesFolder);
      text.onChange(async (value) => {
        this.plugin.settings.notesFolder = value.trim() || DEFAULT_SETTINGS.notesFolder;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Attachments folder").setDesc("Created under the root folder for downloaded Get attachments.").addText((text) => {
      text.setPlaceholder("Attachments");
      text.setValue(this.plugin.settings.attachmentsFolder);
      text.onChange(async (value) => {
        this.plugin.settings.attachmentsFolder = value.trim() || DEFAULT_SETTINGS.attachmentsFolder;
        await this.plugin.savePluginData();
      });
    });
    containerEl.createEl("h3", { text: "Sync behavior" });
    new import_obsidian.Setting(containerEl).setName("Download attachments").setDesc("Download images, audio, video, and files referenced by Get.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.downloadAttachments).onChange(async (value) => {
        this.plugin.settings.downloadAttachments = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include reference content").setDesc("Write the Get ref_content field into each note.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeReferenceText).onChange(async (value) => {
        this.plugin.settings.includeReferenceText = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include original article text").setDesc("Write web_page.content into a separate section when present.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeOriginalText).onChange(async (value) => {
        this.plugin.settings.includeOriginalText = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Inline child notes").setDesc("Render child notes under the parent note instead of syncing them as separate files.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.inlineChildNotes).onChange(async (value) => {
        this.plugin.settings.inlineChildNotes = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto sync on startup").setDesc("Run a sync a few seconds after Obsidian starts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnStartup).onChange(async (value) => {
        this.plugin.settings.autoSyncOnStartup = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto sync interval (hours)").setDesc("Set to 0 to disable scheduled sync.").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("0");
      text.setValue(String(this.plugin.settings.autoSyncIntervalHours));
      text.onChange(async (value) => {
        const parsed = Number.parseInt(value, 10);
        this.plugin.settings.autoSyncIntervalHours = Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
        await this.plugin.savePluginData();
        this.plugin.refreshAutoSyncSchedule();
      });
    });
    containerEl.createEl("h3", { text: "Generated files" });
    new import_obsidian.Setting(containerEl).setName("Generate timeline note").setDesc("Create a grouped overview note with links to all synced files.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.generateTimeline).onChange(async (value) => {
        this.plugin.settings.generateTimeline = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Timeline note path").setDesc("Vault-relative path for the generated timeline note.").addText((text) => {
      text.setPlaceholder("Get/Get Timeline.md");
      text.setValue(this.plugin.settings.timelineNote);
      text.onChange(async (value) => {
        this.plugin.settings.timelineNote = value.trim() || DEFAULT_SETTINGS.timelineNote;
        await this.plugin.savePluginData();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Generate canvas").setDesc("Create a simple Canvas file that links the synced notes as file cards.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.generateCanvas).onChange(async (value) => {
        this.plugin.settings.generateCanvas = value;
        await this.plugin.savePluginData();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Canvas file path").setDesc("Vault-relative path for the generated Canvas file.").addText((text) => {
      text.setPlaceholder("Get/Get Notes.canvas");
      text.setValue(this.plugin.settings.canvasFile);
      text.onChange(async (value) => {
        this.plugin.settings.canvasFile = value.trim() || DEFAULT_SETTINGS.canvasFile;
        await this.plugin.savePluginData();
      });
    });
    containerEl.createEl("h3", { text: "Actions" });
    new import_obsidian.Setting(containerEl).setName("Run sync now").setDesc("Fetch the latest Get notes and write them into this vault.").addButton(
      (button) => button.setButtonText("Sync now").setCta().onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Syncing...");
        try {
          await this.plugin.syncNow("settings");
        } finally {
          button.setDisabled(false);
          button.setButtonText("Sync now");
          this.display();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reset sync state").setDesc("Clear the local sync cache. Existing note files will not be deleted.").addButton(
      (button) => button.setButtonText("Reset").setWarning().onClick(async () => {
        if (!window.confirm("Clear the local sync cache? Existing files in the vault will be kept.")) {
          return;
        }
        await this.plugin.resetSyncState();
        new import_obsidian.Notice("Get sync cache cleared.");
        this.display();
      })
    );
    const summaryEl = containerEl.createDiv({ cls: "get-note-sync-summary" });
    summaryEl.createEl("h3", { text: "Last run" });
    if (!this.plugin.lastSummary) {
      summaryEl.createEl("p", { text: "No sync has completed yet." });
      return;
    }
    const summary = this.plugin.lastSummary;
    summaryEl.createEl("p", { text: `Trigger: ${summary.trigger}` });
    summaryEl.createEl("p", {
      text: `Finished: ${new Date(summary.finishedAt).toLocaleString()}`
    });
    summaryEl.createEl("p", {
      text: `Created ${summary.created}, updated ${summary.updated}, skipped ${summary.skipped}, failed ${summary.failed}.`
    });
    summaryEl.createEl("p", {
      text: `Listed ${summary.totalListed} notes, downloaded ${summary.attachmentsDownloaded} attachments.`
    });
    summaryEl.createEl("p", {
      text: `Timeline ${summary.timelineUpdated ? "updated" : "not updated"}, canvas ${summary.canvasUpdated ? "updated" : "not updated"}.`
    });
  }
};

// src/sync-service.ts
var import_obsidian3 = require("obsidian");

// src/get-client.ts
var import_obsidian2 = require("obsidian");
var GET_API_BASE = "https://openapi.biji.com/open/api/v1";
var GetClient = class {
  constructor(apiKey, clientId) {
    this.headers = {
      Authorization: apiKey,
      "X-Client-ID": clientId
    };
  }
  async listAllNotes() {
    const notes = [];
    let cursor = 0;
    const seen = /* @__PURE__ */ new Set();
    while (true) {
      const key = String(cursor);
      if (seen.has(key)) {
        throw new Error(`Get pagination repeated cursor ${key}.`);
      }
      seen.add(key);
      const response = await this.requestJson(
        "GET",
        "/resource/note/list",
        { since_id: String(cursor) }
      );
      const payload = response.data;
      const batch = (payload?.notes ?? []).map((item) => normalizeNote(item));
      notes.push(...batch);
      if (!payload?.has_more || payload.next_cursor === void 0 || payload.next_cursor === null) {
        break;
      }
      cursor = payload.next_cursor;
    }
    return notes;
  }
  async getNoteDetail(noteId) {
    const response = await this.requestJson(
      "GET",
      "/resource/note/detail",
      { id: noteId }
    );
    const raw = response.data?.note;
    if (!raw) {
      throw new Error(`Get detail response for ${noteId} did not include a note.`);
    }
    return normalizeNote(raw);
  }
  async expandNote(note, seen = /* @__PURE__ */ new Set()) {
    if (seen.has(note.noteId)) {
      return note;
    }
    seen.add(note.noteId);
    const detail = await this.getNoteDetail(note.noteId);
    const childNotes = [];
    for (const childId of detail.childrenIds) {
      if (seen.has(childId)) {
        continue;
      }
      const childDetail = await this.getNoteDetail(childId);
      childNotes.push(await this.expandNote(childDetail, seen));
    }
    detail.childNotes = childNotes;
    return detail;
  }
  async requestJson(method, path, query) {
    const url = new URL(path, `${GET_API_BASE}/`);
    for (const [key, value] of Object.entries(query ?? {})) {
      url.searchParams.set(key, value);
    }
    const response = await (0, import_obsidian2.requestUrl)({
      url: url.toString(),
      method,
      headers: this.headers,
      throw: false
    });
    if (response.status < 200 || response.status >= 300) {
      throw new Error(
        `Get API ${method} ${path} failed with ${response.status}: ${response.text.slice(0, 300)}`
      );
    }
    return response.json;
  }
};
function normalizeNote(raw) {
  const noteId = String(raw.note_id ?? "").trim();
  if (!noteId) {
    throw new Error("Get note payload is missing note_id.");
  }
  const attachments = [];
  for (const item of raw.attachments ?? []) {
    const url = String(item.url ?? "").trim();
    if (!url) {
      continue;
    }
    attachments.push({
      name: String(item.name ?? "").trim() || extractNameFromUrl(url) || `attachment-${noteId}`,
      url,
      contentType: item.content_type ?? item.mime_type
    });
  }
  return {
    noteId,
    title: String(raw.title ?? "").trim() || `Untitled ${noteId}`,
    content: String(raw.content ?? "").trim(),
    refContent: String(raw.ref_content ?? "").trim(),
    noteType: String(raw.note_type ?? "").trim(),
    source: String(raw.source ?? "").trim(),
    tags: collectNames(raw.tags),
    topics: collectNames(raw.topics),
    isChildNote: Boolean(raw.is_child_note),
    childrenCount: Number(raw.children_count ?? 0),
    childrenIds: (raw.children_ids ?? []).map((item) => String(item)),
    parentId: raw.parent_id === void 0 || raw.parent_id === null ? void 0 : String(raw.parent_id),
    attachments,
    webPageUrl: String(raw.web_page?.url ?? "").trim() || void 0,
    originalText: String(raw.web_page?.content ?? "").trim(),
    childNotes: [],
    createdAt: normalizeApiTime(raw.created_at),
    updatedAt: normalizeApiTime(raw.updated_at)
  };
}
function collectNames(values) {
  return (values ?? []).map((item) => String(item.name ?? "").trim()).filter((item) => item.length > 0);
}
function normalizeApiTime(value) {
  if (!value) {
    return void 0;
  }
  const trimmed = value.trim();
  const match = trimmed.match(/^(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}:\d{2})$/);
  if (match) {
    return `${match[1]}T${match[2]}+08:00`;
  }
  return trimmed;
}
function extractNameFromUrl(value) {
  try {
    const url = new URL(value);
    const parts = url.pathname.split("/").filter(Boolean);
    return decodeURIComponent(parts.at(-1) ?? "");
  } catch {
    return "";
  }
}

// src/markdown.ts
function sanitizeFilePart(value) {
  const cleaned = value.replace(/[\\/:*?"<>|]/g, " ").replace(/\s+/g, " ").replace(/[. ]+$/g, "").trim();
  return cleaned.slice(0, 96) || "untitled";
}
function normalizeMarkdown(value) {
  return value.replace(/\r\n/g, "\n").replace(/\r/g, "\n").trim();
}
function hashString(value) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}
function buildRenderConfigHash(settings) {
  return hashString(
    JSON.stringify({
      rootFolder: settings.rootFolder,
      notesFolder: settings.notesFolder,
      attachmentsFolder: settings.attachmentsFolder,
      includeReferenceText: settings.includeReferenceText,
      includeOriginalText: settings.includeOriginalText,
      inlineChildNotes: settings.inlineChildNotes,
      downloadAttachments: settings.downloadAttachments
    })
  );
}
function buildNoteSignature(note, renderConfigHash) {
  return hashString(
    JSON.stringify({
      renderConfigHash,
      noteId: note.noteId,
      title: note.title,
      content: note.content,
      refContent: note.refContent,
      noteType: note.noteType,
      source: note.source,
      tags: note.tags,
      topics: note.topics,
      isChildNote: note.isChildNote,
      childrenCount: note.childrenCount,
      childrenIds: note.childrenIds,
      parentId: note.parentId,
      attachments: note.attachments,
      webPageUrl: note.webPageUrl,
      originalText: note.originalText,
      createdAt: note.createdAt,
      updatedAt: note.updatedAt,
      childNotes: note.childNotes.map((child) => buildNoteSignature(child, renderConfigHash))
    })
  );
}
function buildNoteMarkdown(note, options) {
  const lines = [];
  lines.push("---");
  lines.push(`get_id: ${yamlString(note.noteId)}`);
  lines.push(`get_title: ${yamlString(note.title)}`);
  lines.push(`get_type: ${yamlString(note.noteType || "")}`);
  lines.push(`get_source: ${yamlString(note.source || "")}`);
  lines.push(`get_is_child_note: ${note.isChildNote ? "true" : "false"}`);
  lines.push(`get_children_count: ${note.childrenCount}`);
  lines.push(`get_parent_id: ${yamlString(note.parentId ?? "")}`);
  lines.push(`get_url: ${yamlString(note.webPageUrl ?? "")}`);
  lines.push(`created_at: ${yamlString(note.createdAt ?? "")}`);
  lines.push(`updated_at: ${yamlString(note.updatedAt ?? "")}`);
  lines.push(`synced_at: ${yamlString(options.syncedAt)}`);
  lines.push(`get_tags: ${yamlArray(note.tags)}`);
  lines.push(`get_topics: ${yamlArray(note.topics)}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${note.title}`);
  lines.push("");
  lines.push("> [!info] Get Metadata");
  lines.push(`> ID: ${note.noteId}`);
  if (note.noteType) {
    lines.push(`> Type: ${note.noteType}`);
  }
  if (note.source) {
    lines.push(`> Source: ${note.source}`);
  }
  if (note.createdAt) {
    lines.push(`> Created: ${note.createdAt}`);
  }
  if (note.updatedAt) {
    lines.push(`> Updated: ${note.updatedAt}`);
  }
  if (note.webPageUrl) {
    lines.push(`> Link: [Open source](${note.webPageUrl})`);
  }
  if (note.tags.length > 0) {
    lines.push(`> Tags: ${note.tags.join(", ")}`);
  }
  if (note.topics.length > 0) {
    lines.push(`> Topics: ${note.topics.join(", ")}`);
  }
  pushMarkdownSection(lines, "Note", note.content);
  if (options.includeReferenceText) {
    pushMarkdownSection(lines, "Reference", note.refContent);
  }
  if (options.inlineChildNotes && note.childNotes.length > 0) {
    lines.push("");
    lines.push("## Child Notes");
    for (const child of note.childNotes) {
      renderChildNote(lines, child, 3);
    }
  }
  if (options.includeOriginalText) {
    pushMarkdownSection(lines, "Original Article", note.originalText);
  }
  if (options.attachments.length > 0) {
    lines.push("");
    lines.push("## Attachments");
    lines.push("");
    for (const attachment of options.attachments) {
      if (attachment.downloaded) {
        lines.push(
          attachment.embed ? `![[${attachment.target}]]` : `- [[${attachment.target}|${attachment.name}]]`
        );
      } else {
        lines.push(`- [${attachment.name}](${attachment.target})`);
      }
    }
  }
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trim()}
`;
}
function buildTimelineMarkdown(states, syncedAt) {
  const sorted = [...states].sort(
    (left, right) => compareDates(right.updatedAt ?? right.createdAt, left.updatedAt ?? left.createdAt)
  );
  const lines = [
    "---",
    `title: ${yamlString("Get Timeline")}`,
    `synced_at: ${yamlString(syncedAt)}`,
    "---",
    "",
    "# Get Timeline",
    "",
    `Updated: ${syncedAt}`,
    ""
  ];
  let currentDate = "";
  for (const state of sorted) {
    const bucket = (state.updatedAt ?? state.createdAt ?? "Unknown").slice(0, 10) || "Unknown";
    if (bucket !== currentDate) {
      currentDate = bucket;
      lines.push(`## ${bucket}`);
      lines.push("");
    }
    const stamp = compactTime(state.updatedAt ?? state.createdAt);
    lines.push(`- [[${state.filePath}|${state.title}]]${stamp ? ` (${stamp})` : ""}`);
  }
  return `${lines.join("\n").trim()}
`;
}
function buildCanvasPayload(states, syncedAt) {
  const sorted = [...states].sort(
    (left, right) => compareDates(right.updatedAt ?? right.createdAt, left.updatedAt ?? left.createdAt)
  );
  const columns = 4;
  const cardWidth = 360;
  const cardHeight = 260;
  const gutterX = 60;
  const gutterY = 80;
  const nodes = [
    {
      id: "summary",
      type: "text",
      text: `Get Notes Canvas
Synced: ${syncedAt}
Notes: ${sorted.length}`,
      x: 0,
      y: 0,
      width: 320,
      height: 160
    },
    ...sorted.map((state, index) => {
      const row = Math.floor(index / columns);
      const column = index % columns;
      return {
        id: hashString(`${state.filePath}:${index}`),
        type: "file",
        file: state.filePath,
        x: column * (cardWidth + gutterX),
        y: 220 + row * (cardHeight + gutterY),
        width: cardWidth,
        height: cardHeight
      };
    })
  ];
  return `${JSON.stringify({ nodes, edges: [] }, null, 2)}
`;
}
function pushMarkdownSection(lines, title, body) {
  const normalized = normalizeMarkdown(body);
  if (!normalized) {
    return;
  }
  lines.push("");
  lines.push(`## ${title}`);
  lines.push("");
  lines.push(normalized);
}
function renderChildNote(lines, note, depth) {
  const heading = "#".repeat(Math.min(depth, 6));
  lines.push("");
  lines.push(`${heading} ${note.title}`);
  lines.push("");
  if (note.content) {
    lines.push(normalizeMarkdown(note.content));
  }
  if (note.refContent) {
    lines.push("");
    lines.push(`${"#".repeat(Math.min(depth + 1, 6))} Reference`);
    lines.push("");
    lines.push(normalizeMarkdown(note.refContent));
  }
  for (const child of note.childNotes) {
    renderChildNote(lines, child, depth + 1);
  }
}
function yamlString(value) {
  return JSON.stringify(value);
}
function yamlArray(values) {
  if (values.length === 0) {
    return "[]";
  }
  return `[${values.map((item) => yamlString(item)).join(", ")}]`;
}
function compactTime(value) {
  if (!value) {
    return "";
  }
  const match = value.match(/T(\d{2}:\d{2}:\d{2})/);
  return match?.[1] ?? value;
}
function compareDates(left, right) {
  if (!left && !right) {
    return 0;
  }
  if (!left) {
    return -1;
  }
  if (!right) {
    return 1;
  }
  return left.localeCompare(right);
}

// src/sync-service.ts
var SyncService = class {
  constructor(app, settings, initialState) {
    this.app = app;
    this.settings = settings;
    this.state = { ...initialState };
    this.renderConfigHash = buildRenderConfigHash(settings);
  }
  async sync(trigger) {
    const startedAt = Date.now();
    const client = new GetClient(this.settings.apiKey, this.settings.clientId);
    const listed = await client.listAllNotes();
    const rootNotes = listed.filter((note) => !note.isChildNote).sort((left, right) => sortByMostRecent(right, left));
    let created = 0;
    let updated = 0;
    let skipped = 0;
    let failed = 0;
    let attachmentsDownloaded = 0;
    for (const summary of rootNotes) {
      try {
        if (await this.canSkip(summary)) {
          skipped += 1;
          continue;
        }
        const expanded = await client.expandNote(summary);
        const notePath = this.buildNotePath(expanded);
        const signature = buildNoteSignature(expanded, this.renderConfigHash);
        const existing = this.state[expanded.noteId];
        if (existing && existing.signature === signature && existing.renderConfigHash === this.renderConfigHash && existing.filePath === notePath && await this.fileExists(notePath) && await this.attachmentsHealthy(existing.attachmentPaths)) {
          this.state[expanded.noteId] = {
            ...existing,
            title: expanded.title,
            childrenCount: expanded.childrenCount,
            createdAt: expanded.createdAt,
            updatedAt: expanded.updatedAt
          };
          skipped += 1;
          continue;
        }
        const attachmentResult = await this.syncAttachments(expanded, existing);
        attachmentsDownloaded += attachmentResult.downloadedCount;
        const markdown = buildNoteMarkdown(expanded, {
          syncedAt: (/* @__PURE__ */ new Date()).toISOString(),
          includeReferenceText: this.settings.includeReferenceText,
          includeOriginalText: this.settings.includeOriginalText,
          inlineChildNotes: this.settings.inlineChildNotes,
          attachments: attachmentResult.entries
        });
        await this.writeTextFile(notePath, markdown);
        if (existing?.filePath && existing.filePath !== notePath) {
          await this.removeFile(existing.filePath);
        }
        await this.deleteRemovedAttachments(existing?.attachmentPaths ?? [], attachmentResult.savedPaths);
        this.state[expanded.noteId] = {
          filePath: notePath,
          signature,
          renderConfigHash: this.renderConfigHash,
          title: expanded.title,
          childrenCount: expanded.childrenCount,
          createdAt: expanded.createdAt,
          updatedAt: expanded.updatedAt,
          attachmentPaths: attachmentResult.savedPaths,
          lastSyncedAt: Date.now()
        };
        if (existing) {
          updated += 1;
        } else {
          created += 1;
        }
      } catch (error) {
        failed += 1;
        console.error(`Failed to sync Get note ${summary.noteId}`, error);
      }
    }
    let timelineUpdated = false;
    let canvasUpdated = false;
    const syncedStates = Object.values(this.state);
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    if (this.settings.generateTimeline) {
      await this.writeTextFile(this.settings.timelineNote, buildTimelineMarkdown(syncedStates, nowIso));
      timelineUpdated = true;
    }
    if (this.settings.generateCanvas) {
      await this.writeTextFile(this.settings.canvasFile, buildCanvasPayload(syncedStates, nowIso));
      canvasUpdated = true;
    }
    return {
      trigger,
      totalListed: listed.length,
      rootNotes: rootNotes.length,
      created,
      updated,
      skipped,
      failed,
      attachmentsDownloaded,
      timelineUpdated,
      canvasUpdated,
      startedAt,
      finishedAt: Date.now()
    };
  }
  async canSkip(note) {
    const existing = this.state[note.noteId];
    if (!existing) {
      return false;
    }
    if (existing.renderConfigHash !== this.renderConfigHash) {
      return false;
    }
    if (existing.title !== note.title) {
      return false;
    }
    if (existing.childrenCount !== note.childrenCount) {
      return false;
    }
    if ((existing.updatedAt ?? "") !== (note.updatedAt ?? "")) {
      return false;
    }
    const nextPath = this.buildNotePath(note);
    if (existing.filePath !== nextPath) {
      return false;
    }
    if (!await this.fileExists(existing.filePath)) {
      return false;
    }
    return this.attachmentsHealthy(existing.attachmentPaths);
  }
  async attachmentsHealthy(paths) {
    if (!this.settings.downloadAttachments || paths.length === 0) {
      return true;
    }
    for (const path of paths) {
      if (!await this.fileExists(path)) {
        return false;
      }
    }
    return true;
  }
  buildNotePath(note) {
    const bucket = (note.createdAt ?? note.updatedAt ?? (/* @__PURE__ */ new Date()).toISOString()).slice(0, 10);
    const baseDir = (0, import_obsidian3.normalizePath)(
      `${this.settings.rootFolder}/${this.settings.notesFolder}/${bucket}`
    );
    const fileName = `${sanitizeFilePart(note.title)}--${note.noteId}.md`;
    return (0, import_obsidian3.normalizePath)(`${baseDir}/${fileName}`);
  }
  async syncAttachments(note, existing) {
    if (note.attachments.length === 0) {
      return {
        entries: [],
        savedPaths: [],
        downloadedCount: 0
      };
    }
    const entries = [];
    const savedPaths = [];
    let downloadedCount = 0;
    for (const attachment of note.attachments) {
      const extension = inferExtension(attachment.name, attachment.url, attachment.contentType);
      const attachmentName = extension ? ensureExtension(sanitizeFilePart(stripExtension(attachment.name)), extension) : sanitizeFilePart(attachment.name);
      if (!this.settings.downloadAttachments) {
        entries.push({
          name: attachmentName,
          target: attachment.url,
          downloaded: false,
          embed: isEmbeddable(extension, attachment.contentType)
        });
        continue;
      }
      const targetPath = (0, import_obsidian3.normalizePath)(
        `${this.settings.rootFolder}/${this.settings.attachmentsFolder}/${note.noteId}/${attachmentName}`
      );
      if (!await this.fileExists(targetPath)) {
        const response = await (0, import_obsidian3.requestUrl)({
          url: attachment.url,
          method: "GET",
          throw: false
        });
        if (response.status < 200 || response.status >= 300) {
          throw new Error(`Attachment download failed (${response.status}) for ${attachment.url}`);
        }
        await this.writeBinaryFile(targetPath, response.arrayBuffer);
        downloadedCount += 1;
      }
      savedPaths.push(targetPath);
      entries.push({
        name: attachmentName,
        target: targetPath,
        downloaded: true,
        embed: isEmbeddable(extension, attachment.contentType)
      });
    }
    for (const oldPath of existing?.attachmentPaths ?? []) {
      if (!savedPaths.includes(oldPath) && await this.fileExists(oldPath)) {
        await this.removeFile(oldPath);
      }
    }
    return {
      entries,
      savedPaths,
      downloadedCount
    };
  }
  async deleteRemovedAttachments(previousPaths, nextPaths) {
    for (const path of previousPaths) {
      if (!nextPaths.includes(path) && await this.fileExists(path)) {
        await this.removeFile(path);
      }
    }
  }
  async writeTextFile(path, content) {
    const normalized = (0, import_obsidian3.normalizePath)(path);
    await this.ensureFolder(parentPath(normalized));
    await this.app.vault.adapter.write(normalized, content);
  }
  async writeBinaryFile(path, data) {
    const normalized = (0, import_obsidian3.normalizePath)(path);
    await this.ensureFolder(parentPath(normalized));
    await this.app.vault.adapter.writeBinary(normalized, data);
  }
  async ensureFolder(folderPath) {
    if (!folderPath) {
      return;
    }
    const parts = (0, import_obsidian3.normalizePath)(folderPath).split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!await this.app.vault.adapter.exists(current)) {
        await this.app.vault.createFolder(current);
      }
    }
  }
  async fileExists(path) {
    return this.app.vault.adapter.exists((0, import_obsidian3.normalizePath)(path));
  }
  async removeFile(path) {
    const normalized = (0, import_obsidian3.normalizePath)(path);
    if (await this.app.vault.adapter.exists(normalized)) {
      await this.app.vault.adapter.remove(normalized);
    }
  }
};
function parentPath(path) {
  const segments = (0, import_obsidian3.normalizePath)(path).split("/");
  segments.pop();
  return segments.join("/");
}
function sortByMostRecent(left, right) {
  return compareTimestamps(left.updatedAt ?? left.createdAt, right.updatedAt ?? right.createdAt);
}
function compareTimestamps(left, right) {
  if (!left && !right) {
    return 0;
  }
  if (!left) {
    return -1;
  }
  if (!right) {
    return 1;
  }
  return left.localeCompare(right);
}
function inferExtension(name, url, contentType) {
  const fromName = extractExtension(name);
  if (fromName) {
    return fromName;
  }
  const fromUrl = extractExtension(url);
  if (fromUrl) {
    return fromUrl;
  }
  const lowered = (contentType ?? "").toLowerCase();
  const mapping = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/gif": "gif",
    "image/webp": "webp",
    "audio/mpeg": "mp3",
    "audio/mp4": "m4a",
    "audio/wav": "wav",
    "video/mp4": "mp4",
    "application/pdf": "pdf"
  };
  return mapping[lowered] ?? "";
}
function extractExtension(value) {
  try {
    const pathname = value.includes("://") ? new URL(value).pathname : value;
    const match = pathname.match(/\.([a-zA-Z0-9]{1,10})$/);
    return match?.[1]?.toLowerCase() ?? "";
  } catch {
    return "";
  }
}
function stripExtension(value) {
  return value.replace(/\.[a-zA-Z0-9]{1,10}$/, "");
}
function ensureExtension(value, extension) {
  return value.toLowerCase().endsWith(`.${extension.toLowerCase()}`) ? value : `${value}.${extension}`;
}
function isEmbeddable(extension, contentType) {
  const loweredExtension = extension.toLowerCase();
  const loweredType = (contentType ?? "").toLowerCase();
  return ["png", "jpg", "jpeg", "gif", "webp", "svg", "mp3", "m4a", "wav", "mp4", "pdf"].includes(
    loweredExtension
  ) || loweredType.startsWith("image/") || loweredType.startsWith("audio/") || loweredType.startsWith("video/") || loweredType === "application/pdf";
}

// main.ts
var GetNoteSyncPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.syncedNotes = {};
    this.lastSyncAt = 0;
    this.lastSummary = null;
    this.settingsTab = null;
    this.statusBarEl = null;
    this.syncPromise = null;
    this.syncIntervalId = null;
  }
  async onload() {
    await this.loadPluginData();
    this.settingsTab = new GetSyncSettingTab(this.app, this);
    this.addSettingTab(this.settingsTab);
    this.statusBarEl = this.addStatusBarItem();
    this.updateStatusBar();
    this.addRibbonIcon("refresh-cw", "Sync Get notes now", () => {
      void this.syncNow("ribbon");
    });
    this.addCommand({
      id: "sync-get-notes-now",
      name: "Sync Get notes now",
      callback: () => {
        void this.syncNow("command");
      }
    });
    this.addCommand({
      id: "reset-get-sync-state",
      name: "Reset Get sync state",
      callback: () => {
        void this.resetSyncState();
      }
    });
    this.refreshAutoSyncSchedule();
    if (this.settings.autoSyncOnStartup) {
      window.setTimeout(() => {
        void this.syncNow("startup");
      }, 2e3);
    }
  }
  onunload() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
  }
  async loadPluginData() {
    const data = await this.loadData() ?? {};
    this.settings = { ...DEFAULT_SETTINGS, ...data.settings ?? {} };
    this.syncedNotes = data.syncedNotes ?? {};
    this.lastSyncAt = data.lastSyncAt ?? 0;
    this.lastSummary = data.lastSummary ?? null;
  }
  async savePluginData() {
    await this.saveData({
      settings: this.settings,
      syncedNotes: this.syncedNotes,
      lastSyncAt: this.lastSyncAt,
      lastSummary: this.lastSummary
    });
    this.updateStatusBar();
  }
  validateSettings() {
    if (!this.settings.apiKey.trim()) {
      return "Missing Get API Key in plugin settings.";
    }
    if (!this.settings.clientId.trim()) {
      return "Missing Get Client ID in plugin settings.";
    }
    if (!this.settings.rootFolder.trim()) {
      return "Root folder cannot be empty.";
    }
    if (!this.settings.notesFolder.trim()) {
      return "Notes folder cannot be empty.";
    }
    if (!this.settings.attachmentsFolder.trim()) {
      return "Attachments folder cannot be empty.";
    }
    return null;
  }
  async syncNow(trigger = "manual") {
    if (this.syncPromise) {
      new import_obsidian4.Notice("Get sync is already running.");
      return this.syncPromise;
    }
    const validationError = this.validateSettings();
    if (validationError) {
      new import_obsidian4.Notice(validationError, 8e3);
      return null;
    }
    this.syncPromise = this.runSync(trigger);
    const result = await this.syncPromise.finally(() => {
      this.syncPromise = null;
      this.updateStatusBar();
      this.settingsTab?.display();
    });
    return result;
  }
  async resetSyncState() {
    this.syncedNotes = {};
    this.lastSyncAt = 0;
    this.lastSummary = null;
    await this.savePluginData();
    this.settingsTab?.display();
    new import_obsidian4.Notice("Get sync state has been cleared. Existing files in the vault were left untouched.");
  }
  refreshAutoSyncSchedule() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
    const hours = Number.isFinite(this.settings.autoSyncIntervalHours) ? this.settings.autoSyncIntervalHours : 0;
    if (hours <= 0) {
      return;
    }
    const intervalMs = Math.max(1, hours) * 60 * 60 * 1e3;
    this.syncIntervalId = window.setInterval(() => {
      void this.syncNow("interval");
    }, intervalMs);
  }
  async runSync(trigger) {
    this.updateStatusBar("Get: syncing...");
    try {
      const service = new SyncService(this.app, this.settings, this.syncedNotes);
      const summary = await service.sync(trigger);
      this.syncedNotes = service.state;
      this.lastSyncAt = summary.finishedAt;
      this.lastSummary = summary;
      await this.savePluginData();
      new import_obsidian4.Notice(
        `Get sync finished: +${summary.created} new, ${summary.updated} updated, ${summary.skipped} skipped, ${summary.failed} failed.`,
        9e3
      );
      return summary;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.updateStatusBar("Get: sync failed");
      new import_obsidian4.Notice(`Get sync failed: ${message}`, 1e4);
      throw error;
    }
  }
  updateStatusBar(overrideText) {
    if (!this.statusBarEl) {
      return;
    }
    this.statusBarEl.addClass("get-note-sync-status");
    if (overrideText) {
      this.statusBarEl.setText(overrideText);
      return;
    }
    if (this.syncPromise) {
      this.statusBarEl.setText("Get: syncing...");
      return;
    }
    if (this.lastSyncAt > 0) {
      const at = new Date(this.lastSyncAt).toLocaleString();
      this.statusBarEl.setText(`Get: last sync ${at}`);
      return;
    }
    this.statusBarEl.setText("Get: idle");
  }
};
