name: Sync Get Notes To Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,8 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Run sync
        env:
          GETNOTE_API_KEY: ${{ secrets.GETNOTE_API_KEY }}
          GETNOTE_CLIENT_ID: ${{ secrets.GETNOTE_CLIENT_ID }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python -X utf8 ./sync_get_to_notion.py
